### ISSUE TITLE
    assert self.queue_size % batch_size == 0  # for simplicity

### ISSUE THREAD

**Issue by scarydemon2** [salesforce/BLIP#101]
我自己在进行blip_pretrain的时候，模型会经常在几百个step之后报告assert self.queue_size % batch_size == 0  # for simplicity错误，我想知道哪种情况可能会触发这种错误。我使用的是distributeddataparallel，在4个gpu上4进程训练

When I am doing blip_pretrain myself, the model will often report
“ assert self.queue_size % batch_size == 0 # for simplicity ”error after a few hundred steps,
 I want to know which situation may trigger this error. 
I am using distributeddataparallel with 4 process training on 4 gpus

**Comment by scarydemon2** [comment]
我发现

**Comment by EuterpeK** [comment]
请问是怎么解决的呢？
