### ISSUE TITLE
Why pretrained weights are bigger than finetune weights?

### ISSUE THREAD

**Issue by eeyrw** [salesforce/BLIP#106]
I download:
![image](https://user-images.githubusercontent.com/2088817/194316035-828b5f22-b55f-4257-8c09-3bafbbbeba37.png)
But I find out that pretrained weights is about 3x larger comparing with finetune. What's the difference between them?
When I loading the pretrained weights a message from console saying:
`reshape position embedding from 196 to 576`.
Does it means that two weights correspond to different model configuration?

**Comment by LiJunnan1992** [comment]
1. pretrained weights contains additional parameters such as the momentum model used for contrastive learning.
2. yes the input resolution is different between pretrain & finetune
