### ISSUE TITLE
update to a more recent version of transformers dependency

### ISSUE THREAD

**Issue by jorahn** [salesforce/BLIP#114]
currently blip depends on transformers==4.15.0, which is from december 2021. making blip incompatible to run in the same venv as any current transformers-related project. updating to become compatible with 4.2x would be great.

**Comment by LiJunnan1992** [comment]
Thanks for your comments. Our new LAVIS library supports BLIP with transformers<4.22.0:
https://github.com/salesforce/LAVIS/blob/main/requirements-dev.txt

**Comment by jorahn** [comment]
thank you, i'll give it a try
