### ISSUE TITLE
Unable to download some pretraining data

### ISSUE THREAD

**Issue by wangjk666** [salesforce/BLIP#13]
Hi, when I tried to download the pretraining data using the json files that you provided, I found some images are inaccessible, e.g., http://jaymeswilliams.com/wp-content/uploads/2015/01/DSCN4956_Sal-Cincotta_Big-Blue-Sky_CEP4_Vignette-Lens-1280x924.jpg.

I wonder whether you could directly share the pretraining data?

**Comment by LiJunnan1992** [comment]
Sorry but I don't have the ownership of the images, some of the images could be deleted by their owners. Thanks.
