### ISSUE TITLE
needs for predict demo

### ISSUE THREAD

**Issue by opentld** [salesforce/BLIP#14]
Good job !
would you please release a predict demo ? 
thanks !

**Comment by LiJunnan1992** [comment]
Hi, you can checkout demo.ipynb

**Comment by woctezuma** [comment]
What about this demo?

Integrated into [Huggingface Spaces 🤗](https://huggingface.co/spaces) using [Gradio](https://github.com/gradio-app/gradio). Try out the demo [![Hugging Face Spaces](https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-Spaces-blue)](https://huggingface.co/spaces/akhaliq/BLIP)
