### ISSUE TITLE
Experiment on Action Recognition Datasets like Kinetics

### ISSUE THREAD

**Issue by JunweiLiang** [salesforce/BLIP#15]
Hi, 

Thanks for sharing the good work. I'm wondering if the authors have tried zero-shot / linear-probe experiments on the action recognition datasets like Kinetics-400/600/700? For the CLIP paper and the [Florence paper](https://arxiv.org/pdf/2111.11432.pdf) from MS (Table 10), they have such experiments to quantitatively check the model performance on videos (action recognition, specifically).

Thanks,
Junwei

**Comment by LiJunnan1992** [comment]
Thanks for your question. Since BLIP focuses on tasks with more sophisticated vision-language interaction, we have not experimented with classification tasks.
