### ISSUE TITLE
Text-Video retrieval

### ISSUE THREAD

**Issue by zixuwang1996** [salesforce/BLIP#16]
Dear authors,

I was wondering if you could release the code on text-video retrieval (e.g., dataloader and how you process the videos).

Thanks!

**Comment by LiJunnan1992** [comment]
We will release code for video-text tasks soon, thanks.

**Comment by LiJunnan1992** [comment]
Hi, zero-shot video-text retrieval code has been added, please check the updated readme for instructions. Thanks!

**Comment by cdqncn** [comment]
Dear authors,

I was wondering if you could release the code on text-video qa(e.g., dataloader and how you process the videos).

Thanks!
