### ISSUE TITLE
RuntimeError: The size of tensor a (6) must match the size of tensor b (18) at non-singleton dimension 0

### ISSUE THREAD

**Issue by gpx333** [salesforce/BLIP#161]
models/med.py
    attention_scores = torch.matmul(query_layer, key_layer.transpose(-1, -2))
RuntimeError: The size of tensor a (6) must match the size of tensor b (18) at non-singleton dimension 0

Why is this error reported during the test phase when the training phase is normal?

**Comment by hxy-123-coder** [comment]
Hello, I met the same question, how to sovle it ?

**Comment by uestcMeng** [comment]
I encountered the same error, do you have any solution?
