### ISSUE TITLE
vocab_size of configs/med_config.json

### ISSUE THREAD

**Issue by BlueCat7** [salesforce/BLIP#17]
Hi,
   Thank your nice work! I have a question, when I test captioning I find that vocab_size should be 30524, but do pre-training should be set 30522, am I right? Thanks.

**Comment by LiJunnan1992** [comment]
The vocab_size is 30524 for all tasks, because two new special tokens are add to BERT's vocabulary.

**Comment by BlueCat7** [comment]
> The vocab_size is 30524 for all tasks, because two new special tokens are add to BERT's vocabulary.

Thanks, but the models/blip_pretrain.py line 21, 'configs/Bert_config.json' are not exists. And if I change it to med_config.yaml, it raise vocab_size not matched.

**Comment by LiJunnan1992** [comment]
I use this line of code to match the model's vocab_size with the tokenizer's vocab_size:

`self.text_encoder.resize_token_embeddings(len(self.tokenizer)) `

**Comment by BlueCat7** [comment]
Ok, I see. Thanks!

**Comment by wangjk666** [comment]
so i should change vocab_size in med_config.yaml to 30522, right?

**Comment by LiJunnan1992** [comment]
> so i should change vocab_size in med_config.yaml to 30522, right?

No need to change anything.

**Comment by wangjk666** [comment]
> > The vocab_size is 30524 for all tasks, because two new special tokens are add to BERT's vocabulary.
> 
> Thanks, but the models/blip_pretrain.py line 21, 'configs/Bert_config.json' are not exists. And if I change it to med_config.yaml, it raise vocab_size not matched.

The problem has not been fixed

**Comment by LiJunnan1992** [comment]
bert_config with vocab_size=30522 has been added, thanks!
