### ISSUE TITLE
No scores of VQA evaluation

### ISSUE THREAD

**Issue by p1k0pan** [salesforce/BLIP#181]
I was running `python -m train_vqa.py --evaluate` to try to reproduce the VQA result, but I only get the message of `result file saved to output/VQA/result/vqa_result.json`. And it is using default settings `datasets = create_dataset('vqa', config)   `. Please tell me how to get the final scores. Should I do this by myself?

Thank you!

**Comment by p1k0pan** [comment]
I found that I should work on VQA challenge

**Comment by zijGao** [comment]
Hi! thank you for your sharing. Could you please tell me how to calculate the score?

**Comment by p1k0pan** [comment]
> Hi! thank you for your sharing. Could you please tell me how to calculate the score?

You could visit [VQA-challenge](https://visualqa.org/challenge.html). Use the model generate the answer and evaluate on challenge site

**Comment by zijGao** [comment]
- By the way, is the evaluation score consistent with their reported results?
