### ISSUE TITLE
WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=1800000) Error during Coco Retrieval Evaluation 

### ISSUE THREAD

**Issue by MikeWangWZHL** [salesforce/BLIP#24]
Hi, thanks for sharing this great codebase!

I have been encountering error during evaluation phase on coco_retrieval dataset in train_retrieval, the error happens at the end of the evaluation iterations, on the line:
`torch.distributed.all_reduce(score_matrix_i2t, op=torch.distributed.ReduceOp.SUM)`
The error message is:
`RuntimeError: NCCL communicator was aborted on rank 0.  Original reason for failure was: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(OpType=ALLREDUCE, Timeout(ms)=1800000) ran for 1804984 milliseconds before timing out.`

It is weird that this error is not consistent, in the sense that sometimes when I rerun the same code, I will not get this error. 
I am using 2 V100 gpus, the training phase works well. The error only happens at evaluation time.

Does anyone has any idea of what might be the problem? Thank you!

**Comment by cdqncn** [comment]
I followed the author's readme, and I run it successfully, you may try it again?

**Comment by MikeWangWZHL** [comment]
> I followed the author's readme, and I run it successfully, you may try it again?

It is not occuring consistently (sometimes when I run it the second time, this error does not occur again) , but I still get this problem
