### ISSUE TITLE
fine tune with retrieval_coco.yaml

### ISSUE THREAD

**Issue by BlueCat7** [salesforce/BLIP#26]
Dear Author,
    Thanks for your amazing work. And i have a question about fine-tuning with retrieval_coco.yaml. Why use https://github.com/salesforce/BLIP/blob/main/configs/retrieval_coco.yaml#:~:text=pretrained%3A%20%27https%3A//storage.googleapis.com/sfr%2Dvision%2Dlanguage%2Dresearch/BLIP/models/model_base_retrieval_coco.pth%27 in  retrieval_coco.yaml instead of https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_14M.pth or https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base.pth. 
   Thanks.

**Comment by LiJunnan1992** [comment]
Hi, thanks for your question.
As said in our instruction, the 'pretrained' field in the yaml file need to be changed for finetuning.
