### ISSUE TITLE
Vg_caption

### ISSUE THREAD

**Issue by hhzb123** [salesforce/BLIP#27]
In pretraing status,we use visual genome as part of our training data.But I cannot fing vg_caption.json.Could you tell me where can I download it?

**Comment by LiJunnan1992** [comment]
Hi, you can download it here: https://storage.googleapis.com/sfr-vision-language-research/datasets/vg_caption.json
Note that you need to change the image paths in the json file to your own local paths.

Thanks!

**Comment by hhzb123** [comment]
Does it come from vg region descriptions?

**Comment by LiJunnan1992** [comment]
Yes!

**Comment by hhzb123** [comment]
There are 821k texts in vg_caption.But It's calculated 769k in your papr.So I'd like to know if you use them all for pretaining?

**Comment by LiJunnan1992** [comment]
Yes all texts are used for pretraining, I will modify the paper accordingly, thanks for pointing it out!
