### ISSUE TITLE
Configuration files for large models seem to be missing

### ISSUE THREAD

**Issue by styler00dollar** [salesforce/BLIP#3]
I wanted to try inference with the "large" models, but all I see is config files for the "base" models. How do I use the large models? I think the needed config files are not on Github, while the models itself are available. Would be nice if you could link model and config as a pair of 2 links in the readme, since that would make it easier to see what configuration is for what model. The Colab also only seems to have the base model, which makes it a bit confusing on how to use the large models. Thanks.

**Comment by LiJunnan1992** [comment]
Hi, in order to use the large model, you can simply change the 'vit' in the config from 'base' to 'large'. The batch size and learning rate may need to be adjusted to fit your gpu memory. You can also activate gradient checkpoint in the config file to further reduce memory usage.
