### ISSUE TITLE
Image caption Test code?

### ISSUE THREAD

**Issue by shaoniana1997** [salesforce/BLIP#31]

**Comment by shaoniana1997** [comment]
Hello,Because i am the expert in the image caption, can you share with the url to download the COCO and NoCaps datasets?
Thank you !

**Comment by LiJunnan1992** [comment]
Hi, you can download mscoco here: https://cocodataset.org/#download, and flickr30k here: https://www.kaggle.com/hsankesara/flickr-image-dataset

**Comment by shaoniana1997** [comment]
Thank you for your nice reply! -)

**Comment by woctezuma** [comment]
Just for info, the question here was about the `NoCaps` dataset as well.
