### ISSUE TITLE
Coco and Flickr30 datasets download

### ISSUE THREAD

**Issue by enrico310786** [salesforce/BLIP#33]
HI,
I am a little confused about the number of images and the structure of the COCO and Flickr30 datasets. Could you provide the jsons and urls to which we can find the images, their names and captions in the same train, val and test subdivision that you used?

Thanks in advance

**Comment by LiJunnan1992** [comment]
Hi, you can download mscoco here: https://cocodataset.org/#download, and flickr30k here: https://www.kaggle.com/hsankesara/flickr-image-dataset
