### ISSUE TITLE
Differences in output captions on Colab vs Spaces

### ISSUE THREAD

**Issue by rsanjaykamath** [salesforce/BLIP#34]
Hello, 

When I try the demo on Huggingface Spaces (https://huggingface.co/spaces/Salesforce/BLIP) with a sample image, the output captions are different every time I enter the submit button with same decoding strategy. 

But if I try the code on Colab with the same image and same decoding strategy, the output captions are always the same. 

May I know why this is happening? 

Thanks.

**Comment by woctezuma** [comment]
It must be the seed that is not reset on Colab.

https://github.com/salesforce/BLIP/blob/17dcdd9b7ec6ef88f82dc1319b066d4c3d710f77/eval_nocaps.py#L58-L62

**Comment by LiJunnan1992** [comment]
Hi, the Space demo uses nucleus sampling by default, whereas the colab notebook uses beam search by default.

**Comment by woctezuma** [comment]
Yes, that is what I thought as well, but the results are different at each run with the beam search as well.

**Comment by rsanjaykamath** [comment]
> Hi, the Space demo uses nucleus sampling by default, whereas the colab notebook uses beam search by default.

Hi, Yes I use beam search on both Colab and Spaces. And yet have this issue.

**Comment by rsanjaykamath** [comment]
> Yes, that is what I thought as well, but the results are different at each run of the Space demo **with the beam search as well**.
> 
> ![Beam search option](https://camo.githubusercontent.com/ab79ea6e8954a865756955e16defb32da5f5d83c48bcb41e87622a2064b68172/68747470733a2f2f692e6962622e636f2f66513656526d572f323032322d30332d31372d30392d30342d35302e706e67)
> 
> I have not tested the Colab notebook, but according to the original poster, the results are the same at each run of the Colab demo.

Yes, you're right. 
The issue probably is about the seed, but I do not see where to change it on Colab to get the same behaviour as in Spaces. 

@AK391 I was using the Spaces demo earlier which was on your account (https://huggingface.co/spaces/akhaliq/BLIP) and now moved to another and I had the same behaviour earlier as well. 
Do you know why this behaviour is occurring? 

I would like to replicate this on Colab, that's why I'm interested. 

Thanks in advance.

**Comment by LiJunnan1992** [comment]
Sorry there was a bug in the Spaces demo, it has been fixed and beam search should work now. Thanks!

**Comment by rsanjaykamath** [comment]
> Sorry there was a bug in the Spaces demo, it has been fixed and beam search should work now. Thanks!

Alright. Thanks a lot. 

To summarise this issue, the behaviour of different outputs occurs in "Nucleus Sampling" decoding strategy which is normal and should not occur in "Beam Search" decoding strategy. 

Thanks for fixing the bug in Spaces,  @LiJunnan1992 and your quick response.

**Comment by woctezuma** [comment]
Just for reference, the bug was just a small check:

![Check](https://i.ibb.co/dkMKzXn/2022-03-17-12-19-08.png)

cf. https://huggingface.co/spaces/Salesforce/BLIP/commit/369f0233ed8f85ac73441a877670fa8ebe9e05a5
