### ISSUE TITLE
code

### ISSUE THREAD

**Issue by hhzb123** [salesforce/BLIP#38]
In your code,I noticed that you used momentum update the same as ALBEF, but in your paper you didn't mention it.Why?

**Comment by LiJunnan1992** [comment]
We have mentioned it in the BLIP paper: 
"We follow the ITC loss by Li et al. (2021a), where a momentum encoder
is introduced to produce features, and soft labels are created
from the momentum encoder as training targets to account
for the potential positives in the negative pairs."
