### ISSUE TITLE
which pretrained model should I choose?

### ISSUE THREAD

**Issue by shaoniana1997** [salesforce/BLIP#40]
Hello, nice job in vison language pretraining work, i have a question to bother you .
If i want to train a model , the input is serval key concept, such as : bride groom wedding today , and output concerning sentence related to the above concept, such as :bride and groom have a nice wedding today.
can you give me some advice about how to train this model and which pretrained model should i have?????

**Comment by shaoniana1997** [comment]
or can this BLIP model be used in visual storytelling (variant job such as image caption). visual storytelling:Given five images , and it generates a story consisted of 5 sentences. can you give me some useful advice?????

**Comment by LiJunnan1992** [comment]
Visual storytelling could be possible by fine-tuning the image captioning model.

For your first question, BLIP needs to have image as input.

**Comment by shaoniana1997** [comment]
Thank you for your nice advice -)
