### ISSUE TITLE
Is tensorflow serving enabled?

### ISSUE THREAD

**Issue by joeyouss** [salesforce/BLIP#47]
Hi! Is it possible to use tensorflow serving to serve the model?

**Comment by LiJunnan1992** [comment]
Hi, we only support PyTorch at the moment.

**Comment by joeyouss** [comment]
So, is there any way I can create a REST API for this model?

**Comment by joeyouss** [comment]
So, is there any way I can create a REST API for this model?

**Comment by LiJunnan1992** [comment]
You can checkout our web demo for reference: https://huggingface.co/spaces/Salesforce/BLIP

**Comment by joeyouss** [comment]
Thank you! this helps
