### ISSUE TITLE
Batch predictions mode

### ISSUE THREAD

**Issue by shashi-netra** [salesforce/BLIP#48]
hi, thanks very much for this awesome project. Is a `batch prediction` available. I tried this code and it fails. I couldn't find anything in the samples or documentation for batch mode. Is it on the roadmap, if it's not available now.

```
ref_labels = [...]
image_files = [os.path.join("test_images",f) for f in os.listdir("test_images")]
images = []
for image_file in image_files:
    images.append(load_image(image_file, image_size=384, device=device))
itm_output = model(images, ref_labels, match_head='itm')

```

**Comment by LiJunnan1992** [comment]
Hi, the training and evaluation already operate in batch mode. You need to transform images into pytorch tensors first before giving them to the model.
