### ISSUE TITLE
is zero shot classification supported ?

### ISSUE THREAD

**Issue by subhamkhemka** [salesforce/BLIP#5]
Hi

Thanks for releasing BLIP.

Can I run zero shot classification similar to the OpenAI clip model ?

Thanks,
Subham

**Comment by LiJunnan1992** [comment]
Hi, thanks for your interest in BLIP! Currently we do not support zero-shot classification because different from CLIP, BLIP focuses on tasks that have more sophisticated vision-language interaction. However, we are exploring zero-shot classification using BLIP as a future plan.
