### ISSUE TITLE
The result of caption task is not expected

### ISSUE THREAD

**Issue by liutongyang** [salesforce/BLIP#51]
I used the pre-trained model for the 20th epoch, 

and fine-tuning the caption task for 20 epochs on custom dataset,

the best model‘s results are as follows:

"caption": "post post post post post post post post post post post post post post post post"

The loss value dropped from 6.761 to 6.419. 

Does the model converge? Do you have any good suggestions?

**Comment by LiJunnan1992** [comment]
Can you provide more details about your dataset?
Also, can you successfully fine-tune on COCO?

**Comment by liutongyang** [comment]
I used 80,000 medical dataset [ROCO](https://github.com/razorx89/roco-dataset) for pre-train, this is pre-train hyperparameters, 

<pre>
alpha: 0.4
batch_size: 50
image_size: 224
init_lr: 0.0003
laion_path: ''
lr_decay_rate: 0.9
max_epoch: 500
min_lr: 1e-06
queue_size: 57600
vit: base
vit_ckpt_layer: 0
vit_grad_ckpt: false
warmup_lr: 1e-06
warmup_steps: 3000
weight_decay: 0.05
</pre>

and pre-train log:
<pre>
{"train_lr": "0.000", "train_loss_ita": "8.887", "train_loss_itm": "0.641", "train_loss_lm": "6.829", "epoch": 0}
{"train_lr": "0.000", "train_loss_ita": "7.825", "train_loss_itm": "0.635", "train_loss_lm": "7.079", "epoch": 1}
{"train_lr": "0.000", "train_loss_ita": "7.990", "train_loss_itm": "0.636", "train_loss_lm": "6.823", "epoch": 2}
{"train_lr": "0.000", "train_loss_ita": "8.185", "train_loss_itm": "0.636", "train_loss_lm": "6.694", "epoch": 3}
{"train_lr": "0.000", "train_loss_ita": "8.399", "train_loss_itm": "0.635", "train_loss_lm": "6.620", "epoch": 4}
{"train_lr": "0.000", "train_loss_ita": "8.090", "train_loss_itm": "0.634", "train_loss_lm": "6.565", "epoch": 5}
{"train_lr": "0.000", "train_loss_ita": "8.139", "train_loss_itm": "0.633", "train_loss_lm": "6.540", "epoch": 6}
{"train_lr": "0.000", "train_loss_ita": "8.130", "train_loss_itm": "0.632", "train_loss_lm": "6.490", "epoch": 7}
{"train_lr": "0.000", "train_loss_ita": "8.174", "train_loss_itm": "0.631", "train_loss_lm": "6.449", "epoch": 8}
{"train_lr": "0.000", "train_loss_ita": "8.230", "train_loss_itm": "0.632", "train_loss_lm": "6.403", "epoch": 9}
{"train_lr": "0.000", "train_loss_ita": "8.217", "train_loss_itm": "0.630", "train_loss_lm": "6.370", "epoch": 10}
{"train_lr": "0.000", "train_loss_ita": "8.226", "train_loss_itm": "0.631", "train_loss_lm": "6.338", "epoch": 11}
{"train_lr": "0.000", "train_loss_ita": "8.326", "train_loss_itm": "0.632", "train_loss_lm": "6.342", "epoch": 12}
{"train_lr": "0.000", "train_loss_ita": "8.287", "train_loss_itm": "0.628", "train_loss_lm": "6.281", "epoch": 13}
{"train_lr": "0.000", "train_loss_ita": "8.346", "train_loss_itm": "0.630", "train_loss_lm": "6.238", "epoch": 14}
{"train_lr": "0.000", "train_loss_ita": "8.496", "train_loss_itm": "0.632", "train_loss_lm": "6.193", "epoch": 15}
{"train_lr": "0.000", "train_loss_ita": "8.427", "train_loss_itm": "0.633", "train_loss_lm": "6.155", "epoch": 16}
{"train_lr": "0.000", "train_loss_ita": "8.454", "train_loss_itm": "0.633", "train_loss_lm": "6.121", "epoch": 17}
{"train_lr": "0.000", "train_loss_ita": "8.517", "train_loss_itm": "0.634", "train_loss_lm": "6.087", "epoch": 18}
{"train_lr": "0.000", "train_loss_ita": "8.505", "train_loss_itm": "0.635", "train_loss_lm": "6.058", "epoch": 19}
{"train_lr": "0.000", "train_loss_ita": "8.513", "train_loss_itm": "0.634", "train_loss_lm": "6.028", "epoch": 20}
{"train_lr": "0.000", "train_loss_ita": "8.612", "train_loss_itm": "0.635", "train_loss_lm": "6.003", "epoch": 21}
{"train_lr": "0.000", "train_loss_ita": "8.590", "train_loss_itm": "0.634", "train_loss_lm": "5.979", "epoch": 22}
{"train_lr": "0.000", "train_loss_ita": "8.592", "train_loss_itm": "0.634", "train_loss_lm": "5.956", "epoch": 23}
{"train_lr": "0.000", "train_loss_ita": "8.690", "train_loss_itm": "0.633", "train_loss_lm": "5.938", "epoch": 24}
{"train_lr": "0.000", "train_loss_ita": "8.730", "train_loss_itm": "0.633", "train_loss_lm": "5.916", "epoch": 25}
{"train_lr": "0.000", "train_loss_ita": "8.764", "train_loss_itm": "0.633", "train_loss_lm": "5.899", "epoch": 26}
{"train_lr": "0.000", "train_loss_ita": "8.729", "train_loss_itm": "0.632", "train_loss_lm": "5.885", "epoch": 27}
{"train_lr": "0.000", "train_loss_ita": "8.701", "train_loss_itm": "0.633", "train_loss_lm": "5.869", "epoch": 28}
{"train_lr": "0.000", "train_loss_ita": "8.789", "train_loss_itm": "0.631", "train_loss_lm": "5.856", "epoch": 29}

...

{"train_lr": "0.000", "train_loss_ita": "8.167", "train_loss_itm": "0.615", "train_loss_lm": "5.546", "epoch": 372}
{"train_lr": "0.000", "train_loss_ita": "8.238", "train_loss_itm": "0.618", "train_loss_lm": "5.546", "epoch": 373}
{"train_lr": "0.000", "train_loss_ita": "8.214", "train_loss_itm": "0.616", "train_loss_lm": "5.550", "epoch": 374}
{"train_lr": "0.000", "train_loss_ita": "8.204", "train_loss_itm": "0.615", "train_loss_lm": "5.545", "epoch": 375}
{"train_lr": "0.000", "train_loss_ita": "8.252", "train_loss_itm": "0.616", "train_loss_lm": "5.548", "epoch": 376}
{"train_lr": "0.000", "train_loss_ita": "8.154", "train_loss_itm": "0.616", "train_loss_lm": "5.546", "epoch": 377}
{"train_lr": "0.000", "train_loss_ita": "8.223", "train_loss_itm": "0.614", "train_loss_lm": "5.544", "epoch": 378}
{"train_lr": "0.000", "train_loss_ita": "8.217", "train_loss_itm": "0.614", "train_loss_lm": "5.542", "epoch": 379}
</pre>

<br><br><br><br>

I used 80,000 medical dataset [ImageCLEF](https://www.imageclef.org/) for caption task fine-tune, this is the Hyperparameters and log:

<pre>
batch_size: 24,
 image_size: 384, 
init_lr: 3e-05, 
max_epoch: 20, 
max_length: 20, 
min_length: 5,
min_lr: 1e-09, 
num_beams: 3, 
prompt: 'a picture of ', 
vit: base, 
vit_ckpt_layer: 0, 
vit_grad_ckpt: false, 
weight_decay: 0.05
</pre>

<pre>
{"train_lr": "0.000", "train_loss": "6.276", "val_Bleu_1": 0.04890832522306286, "val_Bleu_2": 1.6965248275796745e-11, "val_Bleu_3": 1.2197582667958834e-14, "val_Bleu_4": 3.331783064146814e-16, "val_METEOR": 0.010383809370451393, "val_ROUGE_L": 0.05218631096106954, "val_CIDEr": 0.003133395348470867, "test_Bleu_1": 0.04890832522306286, "test_Bleu_2": 1.6965248275796745e-11, "test_Bleu_3": 1.2197582667958834e-14, "test_Bleu_4": 3.331783064146814e-16, "test_METEOR": 0.010383809370451393, "test_ROUGE_L": 0.05218631096106954, "test_CIDEr": 0.003133395348470867, "epoch": 0, "best_epoch": 0}
{"train_lr": "0.000", "train_loss": "6.137", "val_Bleu_1": 2.003369475606193e-06, "val_Bleu_2": 1.730038880464872e-15, "val_Bleu_3": 1.685809673719165e-18, "val_Bleu_4": 5.3608178567549355e-20, "val_METEOR": 0.0017136172481017028, "val_ROUGE_L": 0.007819590037119987, "val_CIDEr": 0.00041858634875449466, "test_Bleu_1": 2.003369475606193e-06, "test_Bleu_2": 1.730038880464872e-15, "test_Bleu_3": 1.685809673719165e-18, "test_Bleu_4": 5.3608178567549355e-20, "test_METEOR": 0.0017136172481017028, "test_ROUGE_L": 0.007819590037119987, "test_CIDEr": 0.00041858634875449466, "epoch": 1, "best_epoch": 0}
{"train_lr": "0.000", "train_loss": "6.062", "val_Bleu_1": 4.825325828431883e-151, "val_Bleu_2": 2.375826202730887e-159, "val_Bleu_3": 4.1358528967427173e-162, "val_Bleu_4": 1.757868816603024e-163, "val_METEOR": 5.292605133015046e-05, "val_ROUGE_L": 0.00025923337190966007, "val_CIDEr": 1.183998346807058e-05, "test_Bleu_1": 4.825325828431883e-151, "test_Bleu_2": 2.375826202730887e-159, "test_Bleu_3": 4.1358528967427173e-162, "test_Bleu_4": 1.757868816603024e-163, "test_METEOR": 5.292605133015046e-05, "test_ROUGE_L": 0.00025923337190966007, "test_CIDEr": 1.183998346807058e-05, "epoch": 2, "best_epoch": 0}
{"train_lr": "0.000", "train_loss": "5.994", "val_Bleu_1": 0.0, "val_Bleu_2": 0.0, "val_Bleu_3": 0.0, "val_Bleu_4": 0.0, "val_METEOR": 0.0, "val_ROUGE_L": 0.0, "val_CIDEr": 0.0, "test_Bleu_1": 0.0, "test_Bleu_2": 0.0, "test_Bleu_3": 0.0, "test_Bleu_4": 0.0, "test_METEOR": 0.0, "test_ROUGE_L": 0.0, "test_CIDEr": 0.0, "epoch": 3, "best_epoch": 0}
{"train_lr": "0.000", "train_loss": "5.929", "val_Bleu_1": 0.0, "val_Bleu_2": 0.0, "val_Bleu_3": 0.0, "val_Bleu_4": 0.0, "val_METEOR": 0.0, "val_ROUGE_L": 0.0, "val_CIDEr": 0.0, "test_Bleu_1": 0.0, "test_Bleu_2": 0.0, "test_Bleu_3": 0.0, "test_Bleu_4": 0.0, "test_METEOR": 0.0, "test_ROUGE_L": 0.0, "test_CIDEr": 0.0, "epoch": 4, "best_epoch": 0}
{"train_lr": "0.000", "train_loss": "5.868", "val_Bleu_1": 0.0, "val_Bleu_2": 0.0, "val_Bleu_3": 0.0, "val_Bleu_4": 0.0, "val_METEOR": 0.0, "val_ROUGE_L": 0.0, "val_CIDEr": 0.0, "test_Bleu_1": 0.0, "test_Bleu_2": 0.0, "test_Bleu_3": 0.0, "test_Bleu_4": 0.0, "test_METEOR": 0.0, "test_ROUGE_L": 0.0, "test_CIDEr": 0.0, "epoch": 5, "best_epoch": 0}
{"train_lr": "0.000", "train_loss": "5.814", "val_Bleu_1": 0.0, "val_Bleu_2": 0.0, "val_Bleu_3": 0.0, "val_Bleu_4": 0.0, "val_METEOR": 0.0, "val_ROUGE_L": 0.0, "val_CIDEr": 0.0, "test_Bleu_1": 0.0, "test_Bleu_2": 0.0, "test_Bleu_3": 0.0, "test_Bleu_4": 0.0, "test_METEOR": 0.0, "test_ROUGE_L": 0.0, "test_CIDEr": 0.0, "epoch": 6, "best_epoch": 0}
{"train_lr": "0.000", "train_loss": "5.767", "val_Bleu_1": 0.0, "val_Bleu_2": 0.0, "val_Bleu_3": 0.0, "val_Bleu_4": 0.0, "val_METEOR": 0.0, "val_ROUGE_L": 0.0, "val_CIDEr": 0.0, "test_Bleu_1": 0.0, "test_Bleu_2": 0.0, "test_Bleu_3": 0.0, "test_Bleu_4": 0.0, "test_METEOR": 0.0, "test_ROUGE_L": 0.0, "test_CIDEr": 0.0, "epoch": 7, "best_epoch": 0}
{"train_lr": "0.000", "train_loss": "5.720", "val_Bleu_1": 0.0, "val_Bleu_2": 0.0, "val_Bleu_3": 0.0, "val_Bleu_4": 0.0, "val_METEOR": 0.0, "val_ROUGE_L": 0.0, "val_CIDEr": 0.0, "test_Bleu_1": 0.0, "test_Bleu_2": 0.0, "test_Bleu_3": 0.0, "test_Bleu_4": 0.0, "test_METEOR": 0.0, "test_ROUGE_L": 0.0, "test_CIDEr": 0.0, "epoch": 8, "best_epoch": 0}
{"train_lr": "0.000", "train_loss": "5.668", "val_Bleu_1": 5.469666662710366e-129, "val_Bleu_2": 2.3871582388614487e-137, "val_Bleu_3": 3.9918639577933225e-140, "val_Bleu_4": 1.6629116081117012e-141, "val_METEOR": 6.735799828868586e-05, "val_ROUGE_L": 0.0003433592155789967, "val_CIDEr": 2.5290043766462548e-05, "test_Bleu_1": 5.469666662710366e-129, "test_Bleu_2": 2.3871582388614487e-137, "test_Bleu_3": 3.9918639577933225e-140, "test_Bleu_4": 1.6629116081117012e-141, "test_METEOR": 6.735799828868586e-05, "test_ROUGE_L": 0.0003433592155789967, "test_CIDEr": 2.5290043766462548e-05, "epoch": 9, "best_epoch": 0}
{"train_lr": "0.000", "train_loss": "5.619", "val_Bleu_1": 0.021124817613873206, "val_Bleu_2": 8.893674653820952e-12, "val_Bleu_3": 6.8207437852202916e-15, "val_Bleu_4": 1.9242130501231726e-16, "val_METEOR": 0.007036319974253944, "val_ROUGE_L": 0.03524115115910063, "val_CIDEr": 0.002092899395884595, "test_Bleu_1": 0.021124817613873206, "test_Bleu_2": 8.893674653820952e-12, "test_Bleu_3": 6.8207437852202916e-15, "test_Bleu_4": 1.9242130501231726e-16, "test_METEOR": 0.007036319974253944, "test_ROUGE_L": 0.03524115115910063, "test_CIDEr": 0.002092899395884595, "epoch": 10, "best_epoch": 0}
{"train_lr": "0.000", "train_loss": "5.580", "val_Bleu_1": 0.07222416612825072, "val_Bleu_2": 0.0006803692301485956, "val_Bleu_3": 1.4703468024527733e-09, "val_Bleu_4": 2.2019300118016916e-12, "val_METEOR": 0.013705741270949284, "val_ROUGE_L": 0.06844573717311263, "val_CIDEr": 0.003998480976808383, "test_Bleu_1": 0.07222416612825072, "test_Bleu_2": 0.0006803692301485956, "test_Bleu_3": 1.4703468024527733e-09, "test_Bleu_4": 2.2019300118016916e-12, "test_METEOR": 0.013705741270949284, "test_ROUGE_L": 0.06844573717311263, "test_CIDEr": 0.003998480976808383, "epoch": 11, "best_epoch": 11}
{"train_lr": "0.000", "train_loss": "5.543", "val_Bleu_1": 0.07227496472200488, "val_Bleu_2": 0.0006806496016371594, "val_Bleu_3": 1.4708099907720835e-09, "val_Bleu_4": 2.2025168031776155e-12, "val_METEOR": 0.013713441331423753, "val_ROUGE_L": 0.06847520533412102, "val_CIDEr": 0.003998636739930579, "test_Bleu_1": 0.07227496472200488, "test_Bleu_2": 0.0006806496016371594, "test_Bleu_3": 1.4708099907720835e-09, "test_Bleu_4": 2.2025168031776155e-12, "test_METEOR": 0.013713441331423753, "test_ROUGE_L": 0.06847520533412102, "test_CIDEr": 0.003998636739930579, "epoch": 12, "best_epoch": 12}
{"train_lr": "0.000", "train_loss": "5.514", "val_Bleu_1": 0.07227496472200488, "val_Bleu_2": 0.0006806496016371594, "val_Bleu_3": 1.4708099907720835e-09, "val_Bleu_4": 2.2025168031776155e-12, "val_METEOR": 0.013713441331423753, "val_ROUGE_L": 0.06847520533412102, "val_CIDEr": 0.003998636739930579, "test_Bleu_1": 0.07227496472200488, "test_Bleu_2": 0.0006806496016371594, "test_Bleu_3": 1.4708099907720835e-09, "test_Bleu_4": 2.2025168031776155e-12, "test_METEOR": 0.013713441331423753, "test_ROUGE_L": 0.06847520533412102, "test_CIDEr": 0.003998636739930579, "epoch": 13, "best_epoch": 12}
{"train_lr": "0.000", "train_loss": "5.490", "val_Bleu_1": 0.07227496472200488, "val_Bleu_2": 0.0006806496016371594, "val_Bleu_3": 1.4708099907720835e-09, "val_Bleu_4": 2.2025168031776155e-12, "val_METEOR": 0.013713441331423753, "val_ROUGE_L": 0.06847520533412102, "val_CIDEr": 0.003998636739930579, "test_Bleu_1": 0.07227496472200488, "test_Bleu_2": 0.0006806496016371594, "test_Bleu_3": 1.4708099907720835e-09, "test_Bleu_4": 2.2025168031776155e-12, "test_METEOR": 0.013713441331423753, "test_ROUGE_L": 0.06847520533412102, "test_CIDEr": 0.003998636739930579, "epoch": 14, "best_epoch": 12}
{"train_lr": "0.000", "train_loss": "5.468", "val_Bleu_1": 0.07227496472200488, "val_Bleu_2": 0.0006806496016371594, "val_Bleu_3": 1.4708099907720835e-09, "val_Bleu_4": 2.2025168031776155e-12, "val_METEOR": 0.013713441331423753, "val_ROUGE_L": 0.06847520533412102, "val_CIDEr": 0.003998636739930579, "test_Bleu_1": 0.07227496472200488, "test_Bleu_2": 0.0006806496016371594, "test_Bleu_3": 1.4708099907720835e-09, "test_Bleu_4": 2.2025168031776155e-12, "test_METEOR": 0.013713441331423753, "test_ROUGE_L": 0.06847520533412102, "test_CIDEr": 0.003998636739930579, "epoch": 15, "best_epoch": 12}
{"train_lr": "0.000", "train_loss": "5.456", "val_Bleu_1": 0.07227496472200488, "val_Bleu_2": 0.0006806496016371594, "val_Bleu_3": 1.4708099907720835e-09, "val_Bleu_4": 2.2025168031776155e-12, "val_METEOR": 0.013713441331423753, "val_ROUGE_L": 0.06847520533412102, "val_CIDEr": 0.003998636739930579, "test_Bleu_1": 0.07227496472200488, "test_Bleu_2": 0.0006806496016371594, "test_Bleu_3": 1.4708099907720835e-09, "test_Bleu_4": 2.2025168031776155e-12, "test_METEOR": 0.013713441331423753, "test_ROUGE_L": 0.06847520533412102, "test_CIDEr": 0.003998636739930579, "epoch": 16, "best_epoch": 12}
{"train_lr": "0.000", "train_loss": "5.442", "val_Bleu_1": 0.07227496472200488, "val_Bleu_2": 0.0006806496016371594, "val_Bleu_3": 1.4708099907720835e-09, "val_Bleu_4": 2.2025168031776155e-12, "val_METEOR": 0.013713441331423753, "val_ROUGE_L": 0.06847520533412102, "val_CIDEr": 0.003998636739930579, "test_Bleu_1": 0.07227496472200488, "test_Bleu_2": 0.0006806496016371594, "test_Bleu_3": 1.4708099907720835e-09, "test_Bleu_4": 2.2025168031776155e-12, "test_METEOR": 0.013713441331423753, "test_ROUGE_L": 0.06847520533412102, "test_CIDEr": 0.003998636739930579, "epoch": 17, "best_epoch": 12}
{"train_lr": "0.000", "train_loss": "5.436", "val_Bleu_1": 0.07227496472200488, "val_Bleu_2": 0.0006806496016371594, "val_Bleu_3": 1.4708099907720835e-09, "val_Bleu_4": 2.2025168031776155e-12, "val_METEOR": 0.013713441331423753, "val_ROUGE_L": 0.06847520533412102, "val_CIDEr": 0.003998636739930579, "test_Bleu_1": 0.07227496472200488, "test_Bleu_2": 0.0006806496016371594, "test_Bleu_3": 1.4708099907720835e-09, "test_Bleu_4": 2.2025168031776155e-12, "test_METEOR": 0.013713441331423753, "test_ROUGE_L": 0.06847520533412102, "test_CIDEr": 0.003998636739930579, "epoch": 18, "best_epoch": 12}
{"train_lr": "0.000", "train_loss": "5.432", "val_Bleu_1": 0.07227496472200488, "val_Bleu_2": 0.0006806496016371594, "val_Bleu_3": 1.4708099907720835e-09, "val_Bleu_4": 2.2025168031776155e-12, "val_METEOR": 0.013713441331423753, "val_ROUGE_L": 0.06847520533412102, "val_CIDEr": 0.003998636739930579, "test_Bleu_1": 0.07227496472200488, "test_Bleu_2": 0.0006806496016371594, "test_Bleu_3": 1.4708099907720835e-09, "test_Bleu_4": 2.2025168031776155e-12, "test_METEOR": 0.013713441331423753, "test_ROUGE_L": 0.06847520533412102, "test_CIDEr": 0.003998636739930579, "epoch": 19, "best_epoch": 12}
</pre>

This is a partial result
<pre>
{"image_id": 2694710714, "caption": "the the the the the the the the the the the the the the the the"},
{"image_id": 3777005461, "caption": "the the the the the the the the the the the the the the the the"}, 
{"image_id": 9053632190, "caption": "the the the the the the the the the the the the the the the the"},
{"image_id": 1222306388, "caption": "the the the the the the the the the the the the the the the the"}, 
</pre>

Can you see where the problem is？
and I have not fine-tuned on the COCO dataset.

By the way, happy May Day~

**Comment by LiJunnan1992** [comment]
Thanks. Are you using my pre-trained checkpoint?

**Comment by liutongyang** [comment]
Not yet, 

the above results are from the 100th pre-train epoch and the 20th fine-tune epoch.

I now try to replace your checkpoint.

**Comment by liutongyang** [comment]
The result of finetune on ImageCLEF based on "model_base_capfilt_large.pth" seems to be good, at least the result is a smooth sentence, the training log on the best epoch is as follows：
<pre>
{
    "train_lr": "0.000",
    "train_loss": "3.015",
    "val_Bleu_1": 0.11095367782859003,
    "val_Bleu_2": 0.06417032491365265,
    "val_Bleu_3": 0.03696562573804606,
    "val_Bleu_4": 0.02232537363069134,
    "val_METEOR": 0.07324724878327207,
    "val_ROUGE_L": 0.19027647993354468,
    "val_CIDEr": 0.22511703121247736,
    "test_Bleu_1": 0.11095367782859003,
    "test_Bleu_2": 0.06417032491365265,
    "test_Bleu_3": 0.03696562573804606,
    "test_Bleu_4": 0.02232537363069134,
    "test_METEOR": 0.07324724878327207,
    "test_ROUGE_L": 0.19027647993354468,
    "test_CIDEr": 0.22511703121247736,
    "epoch": 11,
    "best_epoch": 11
}
</pre>

I noticed that the paper reported using 14M images for pre-training, I only used 80K images for pre-training, probably this is the reason for the poor effect.

Can I continue pre-training by adding 80K ROCO corpus based on your open source checkpoint? How does the code need to be changed?

**Comment by LiJunnan1992** [comment]
yes you can try to continue pretraining using your data.

**Comment by liutongyang** [comment]
thanks
