### ISSUE TITLE
problem with pretraining

### ISSUE THREAD

**Issue by MEICHENZI** [salesforce/BLIP#53]
Hi， I have always had this problem in pre-training, where is this address?
FileNotFoundError: [Errno 2] No such file or directory: '/export/share/datasets/vision/visual-genome/image/2350675.jpg'

**Comment by woctezuma** [comment]
From the README:

> Download VQA v2 dataset and Visual Genome dataset from the original websites, and set 'vqa_root' and 'vg_root' in configs/vqa.yaml.

https://github.com/salesforce/BLIP/blob/e54c601766f72aa9476e4dc9376d8bec71642bd1/configs/vqa.yaml#L1-L2

**Comment by MEICHENZI** [comment]
Thank you for your reply, the problem has been solved. But the reason for the problem was that I didn't change the address in the file vg_caption.json before, thanks again for your reply
