### ISSUE TITLE
question about Bootstrap captions from noisy image-text pairs?

### ISSUE THREAD

**Issue by trouble-maker007** [salesforce/BLIP#54]
Is there any example scripts about how to use the pretrain checkpoint to Bootstrap captions from noisy image-text pairs, then get the much more cleaning train data?

**Comment by LiJunnan1992** [comment]
You can check out our demo code, where we provide both the captioning script and image-text matching script that you can use to bootstrap.

**Comment by trouble-maker007** [comment]
thanks for response, the bootstrap step should like following::

1.use the captioning script to generate the image caption
2.then use the image-text matching script to compare the origin one and caption,
3.if the caption one or origin one similarity score bigger than setting threshold, keep the more similar one

and I still have some question:
1. if both lower than the than setting threshold, the image-text is likely to delete from the training data
2. would you like to provide the setting threshold value, **bigger than 0.8**?

**Comment by LiJunnan1992** [comment]
The steps are:
1. generate synthetic captions
2. combine synthetic and original captions, and remove all captions that have a similarity score below 0.5

**Comment by yzqinjacob** [comment]
I have the same question about how to utilize Bootstrap as follows:
There are various versions of finetuned checkpoints in your released page, and which version is supposed to use for filter & which for captioner? 
Thanks for your reply.

**Comment by trouble-maker007** [comment]
@LiJunnan1992 
Got it, I still have the last question, the similarity score is use the cosine similarity, 
for example in the demo : `The image feature and text feature has a cosine similarity of 0.5262`, 
that the text image keep, otherwise remove

**Comment by LiJunnan1992** [comment]
@trouble-maker007 We used the image-text matching score, although you can also use the cosine similarity.

**Comment by LiJunnan1992** [comment]
> I have the same question about how to utilize Bootstrap as follows: There are various versions of finetuned checkpoints in your released page, and which version is supposed to use for filter & which for captioner? Thanks for your reply.

@yzqinjacob We used the coco's caption model as captioner, and coco's retrieval model as filter.

**Comment by trouble-maker007** [comment]
@LiJunnan1992 Thank you very much for your detailed answer

**Comment by yzqinjacob** [comment]
@LiJunnan1992 Thansk for your reply and it helps me a lot.
