### ISSUE TITLE
Confidence score in image captioning

### ISSUE THREAD

**Issue by helleuch** [salesforce/BLIP#61]
Hello,
I am using BLIP for image captioning. And I would like to retrieve a confidence score about the generated caption. Is there a way to do this ?

**Comment by LiJunnan1992** [comment]
The decoder cannot provide a confidence score directly. You can use the encoder to measure the image-text matching similarity, which gives a measurement of how well the caption describes the image

**Comment by helleuch** [comment]
Thank you for your answer ! I indeed did what you suggested.

**Comment by shrijayan** [comment]
> The decoder cannot provide a confidence score directly. You can use the encoder to compute the image-text matching score, which gives a measurement of how well the caption describes the image

I am using BLIP Visual Question answering is there any possibility of calculating the confidence score for this? 

Or please describe still more if possible with an example to use the encoder to compute the image-text matching score, which gives a measurement of how well the caption describes the image
