### ISSUE TITLE
Details about Visual-genome Dataset

### ISSUE THREAD

**Issue by FingerRec** [salesforce/BLIP#79]
Thanks for this good work!

I find there are two image parts in https://visualgenome.org/api/v0/api_home.html.

But the vg_caption.json not indicated how to process these two subset.

Can you kindly provide more details about processing vg dataset?

BTW, you use V1.0 or V1.1 for VG?

**Comment by woctezuma** [comment]
Maybe related:
- #27

**Comment by FingerRec** [comment]
Solved. thanks for your timely feedback
