### ISSUE TITLE
visualize BLIP attention

### ISSUE THREAD

**Issue by nikky4D** [salesforce/BLIP#80]
Is there a way to visualize what/where blip focuses in an image when given an input text? similar to grad cam for visualizing weights

**Comment by LiJunnan1992** [comment]
Hi, you can use this code to visualize the gradcam on cross-attention maps for BLIP:

https://github.com/salesforce/ALBEF/blob/main/visualization.ipynb

**Comment by nikky4D** [comment]
Thank you. I'll take a look.

**Comment by BoomShakaY** [comment]
I have the same question about visualizations.
