### ISSUE TITLE
Filter and Captioner

### ISSUE THREAD

**Issue by baolp** [salesforce/BLIP#86]
Hi， thanks for your outstanding work.

I don't find the usage of Filter and Captioner in blip_pretrain.py. 

Do you provide this code?

Thanks

**Comment by KosukeTrue** [comment]
hello, can you share the details about the code of Filter and Captioner?

**Comment by LiJunnan1992** [comment]
Hi, the filter is the retrieval model finetuned on COCO. The captioner is the captioning model finetuned on COCO.

**Comment by aries-young** [comment]
> Hi, the filter is the retrieval model finetuned on COCO. The captioner is the captioning model finetuned on COCO.

Hi, could you please kindly provide the code of the process of Dataset Bootstrapping？
