### ISSUE TITLE
some unknown error during run "train_retrieval.py "

### ISSUE THREAD

**Issue by SKBL5694** [salesforce/BLIP#90]
Because I don't have enough GPUs, so I use 4 1080ti for this code:
`python -m torch.distributed.run --nproc_per_node=4 train_retrieval.py --config ./configs/retrieval_coco.yaml --output_dir output/retrieval_coco`
and I change the both the train and the test batch size in the config file: batch_size_train: 4 batch_size_test: 4.
The program can run correctly during traing, but once training is over, the program tries the evaluation: it raise an error I can not find the solution on google.
Some errors are as follows:

'''
Train Epoch: [0]  [35420/35421]  eta: 0:00:02  lr: 0.000010  loss_itm: 0.3562  loss_ita: 2.3850  time: 2.3793  data: 0.0020  max mem: 8854
Train Epoch: [0] Total time: 22:40:08 (2.3040 s / it)
Averaged stats: lr: 0.0000  loss_itm: 0.1165  loss_ita: 2.0232
Computing features for evaluation...
Evaluation:  [   0/1251]  eta: 21 days, 12:31:33    time: 1486.4058  data: 8.5921  max mem: 8854
[ERROR] 2022-08-21 20:11:07,312 api: failed (exitcode: -9) local_rank: 0 (pid: 28413) of binary: /home/xuzhiyuan/anaconda3/envs/torch19/bin/python
[ERROR] 2022-08-21 20:11:08,697 local_elastic_agent: [default] Worker group failed
[INFO] 2022-08-21 20:11:08,757 api: [default] Worker group FAILED. 3/3 attempts left; will restart worker group
[INFO] 2022-08-21 20:11:08,758 api: [default] Stopping worker group
[INFO] 2022-08-21 20:11:08,773 api: [default] Rendezvous'ing worker group
[INFO] 2022-08-21 20:11:08,773 static_tcp_rendezvous: Creating TCPStore as the c10d::Store implementation
[INFO] 2022-08-21 20:11:11,234 api: [default] Rendezvous complete for workers. Result:
  restart_count=1
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0, 1, 2, 3]
  role_ranks=[0, 1, 2, 3]
  global_ranks=[0, 1, 2, 3]
  role_world_sizes=[4, 4, 4, 4]
  global_world_sizes=[4, 4, 4, 4]

[INFO] 2022-08-21 20:11:11,292 api: [default] Starting worker group
[INFO] 2022-08-21 20:11:11,500 __init__: Setting worker0 reply file to: /tmp/torchelastic_xlr45rnk/none_9bbx_br0/attempt_1/0/error.json
[INFO] 2022-08-21 20:11:11,501 __init__: Setting worker1 reply file to: /tmp/torchelastic_xlr45rnk/none_9bbx_br0/attempt_1/1/error.json
[INFO] 2022-08-21 20:11:11,501 __init__: Setting worker2 reply file to: /tmp/torchelastic_xlr45rnk/none_9bbx_br0/attempt_1/2/error.json
[INFO] 2022-08-21 20:11:11,501 __init__: Setting worker3 reply file to: /tmp/torchelastic_xlr45rnk/none_9bbx_br0/attempt_1/3/error.json
| distributed init (rank 2, word 4): env://
| distributed init (rank 0, word 4): env://
| distributed init (rank 3, word 4): env://
| distributed init (rank 1, word 4): env://
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "train_retrieval.py", line 345, in <module>
  File "train_retrieval.py", line 345, in <module>
  File "train_retrieval.py", line 345, in <module>
  File "train_retrieval.py", line 345, in <module>
    main(args, config)
  File "train_retrieval.py", line 219, in main
    main(args, config)
    main(args, config)  File "train_retrieval.py", line 219, in main
main(args, config)

  File "train_retrieval.py", line 219, in main
  File "train_retrieval.py", line 219, in main
    utils.init_distributed_mode(args)
  File "/home/xuzhiyuan/project/BLIP/utils.py", line 273, in init_distributed_mode
    utils.init_distributed_mode(args)
    utils.init_distributed_mode(args)      File "/home/xuzhiyuan/project/BLIP/utils.py", line 273, in init_distributed_mode

  File "/home/xuzhiyuan/project/BLIP/utils.py", line 273, in init_distributed_mode
    utils.init_distributed_mode(args)
  File "/home/xuzhiyuan/project/BLIP/utils.py", line 273, in init_distributed_mode
    torch.distributed.init_process_group(backend=args.dist_backend, init_method=args.dist_url,
  File "/home/xuzhiyuan/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 547, in init_process_group
        torch.distributed.init_process_group(backend=args.dist_backend, init_method=args.dist_url,torch.distributed.init_process_group(backend=args.dist_backend, init_method=args.dist_url,

File "/home/xuzhiyuan/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 547, in init_process_group
  File "/home/xuzhiyuan/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 547, in init_process_group
torch.distributed.init_process_group(backend=args.dist_backend, init_method=args.dist_url,
  File "/home/xuzhiyuan/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 547, in init_process_group
            _store_based_barrier(rank, store, timeout)    _store_based_barrier(rank, store, timeout)_store_based_barrier(rank, store, timeout)
_store_based_barrier(rank, store, timeout)

  File "/home/xuzhiyuan/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 219, in _store_based_barrier
  File "/home/xuzhiyuan/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 219, in _store_based_barrier
  File "/home/xuzhiyuan/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 219, in _store_based_barrier
  File "/home/xuzhiyuan/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 219, in _store_based_barrier
    raise RuntimeError(
            raise RuntimeError(raise RuntimeError(RuntimeErrorraise RuntimeError(

:
Timed out initializing process group in store based barrier on rank: 3, for key: store_based_barrier_key:1 (world_size=4, worker_count=8, timeout=0:30:00)
RuntimeError: RuntimeErrorTimed out initializing process group in store based barrier on rank: 2, for key: store_based_barrier_key:1 (world_size=4, worker_count=8, timeout=0:30:00):
Timed out initializing process group in store based barrier on rank: 0, for key: store_based_barrier_key:1 (world_size=4, worker_count=8, timeout=0:30:00)RuntimeError
: Timed out initializing process group in store based barrier on rank: 1, for key: store_based_barrier_key:1 (world_size=4, worker_count=8, timeout=0:30:00)
'''

and this will repeat 3 times then it raise another error with a long logs. Since the following error is also very long, I will not list it for now. 

Can you give some advice to solve this problem? By the way, the first time I met this, I think the reason is the cuda memory is not enough, so I change the test_batch_size from 8 to 4. But it still raise some errors .
Sorry to bother you, hope to get your reply.

**Comment by SKBL5694** [comment]
after 3 times same error, the following error message is this:

'''
[ERROR] 2022-08-21 21:41:48,161 api: failed (exitcode: 1) local_rank: 0 (pid: 16500) of binary: /home/xuzhiyuan/anaconda3/envs/torch19/bin/python
[ERROR] 2022-08-21 21:41:48,161 local_elastic_agent: [default] Worker group failed
[INFO] 2022-08-21 21:41:48,214 api: Local worker group finished (FAILED). Waiting 300 seconds for other agents to finish
/home/xuzhiyuan/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/distributed/elastic/utils/store.py:70: FutureWarning: This is an experimental API and will be changed in future.
  warnings.warn(
[INFO] 2022-08-21 21:41:48,287 api: Done waiting for other agents. Elapsed: 0.07299566268920898 seconds
{"name": "torchelastic.worker.status.FAILED", "source": "WORKER", "timestamp": 0, "metadata": {"run_id": "none", "global_rank": 0, "group_rank": 0, "worker_id": "16500", "role": "default", "hostname": "k8s-node1", "state": "FAILED", "total_run_time": 100192, "rdzv_backend": "static", "raw_error": "{\"message\": \"<NONE>\"}", "metadata": "{\"group_world_size\": 1, \"entry_point\": \"python\", \"local_rank\": [0], \"role_rank\": [0], \"role_world_size\": [4]}", "agent_restarts": 3}}
{"name": "torchelastic.worker.status.FAILED", "source": "WORKER", "timestamp": 0, "metadata": {"run_id": "none", "global_rank": 1, "group_rank": 0, "worker_id": "16501", "role": "default", "hostname": "k8s-node1", "state": "FAILED", "total_run_time": 100192, "rdzv_backend": "static", "raw_error": "{\"message\": \"<NONE>\"}", "metadata": "{\"group_world_size\": 1, \"entry_point\": \"python\", \"local_rank\": [1], \"role_rank\": [1], \"role_world_size\": [4]}", "agent_restarts": 3}}
{"name": "torchelastic.worker.status.FAILED", "source": "WORKER", "timestamp": 0, "metadata": {"run_id": "none", "global_rank": 2, "group_rank": 0, "worker_id": "16502", "role": "default", "hostname": "k8s-node1", "state": "FAILED", "total_run_time": 100192, "rdzv_backend": "static", "raw_error": "{\"message\": \"<NONE>\"}", "metadata": "{\"group_world_size\": 1, \"entry_point\": \"python\", \"local_rank\": [2], \"role_rank\": [2], \"role_world_size\": [4]}", "agent_restarts": 3}}
{"name": "torchelastic.worker.status.FAILED", "source": "WORKER", "timestamp": 0, "metadata": {"run_id": "none", "global_rank": 3, "group_rank": 0, "worker_id": "16503", "role": "default", "hostname": "k8s-node1", "state": "FAILED", "total_run_time": 100192, "rdzv_backend": "static", "raw_error": "{\"message\": \"<NONE>\"}", "metadata": "{\"group_world_size\": 1, \"entry_point\": \"python\", \"local_rank\": [3], \"role_rank\": [3], \"role_world_size\": [4]}", "agent_restarts": 3}}
{"name": "torchelastic.worker.status.SUCCEEDED", "source": "AGENT", "timestamp": 0, "metadata": {"run_id": "none", "global_rank": null, "group_rank": 0, "worker_id": null, "role": "default", "hostname": "k8s-node1", "state": "SUCCEEDED", "total_run_time": 100193, "rdzv_backend": "static", "raw_error": null, "metadata": "{\"group_world_size\": 1, \"entry_point\": \"python\"}", "agent_restarts": 3}}
/home/xuzhiyuan/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py:354: UserWarning:

**********************************************************************
               CHILD PROCESS FAILED WITH NO ERROR_FILE
**********************************************************************
CHILD PROCESS FAILED WITH NO ERROR_FILE
Child process 16500 (local_rank 0) FAILED (exitcode 1)
Error msg: Process failed with exitcode 1
Without writing an error file to <N/A>.
While this DOES NOT affect the correctness of your application,
no trace information about the error will be available for inspection.
Consider decorating your top level entrypoint function with
torch.distributed.elastic.multiprocessing.errors.record. Example:

  from torch.distributed.elastic.multiprocessing.errors import record

  @record
  def trainer_main(args):
     # do train
**********************************************************************
  warnings.warn(_no_error_file_warning_msg(rank, failure))
Traceback (most recent call last):
  File "/home/xuzhiyuan/anaconda3/envs/torch19/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xuzhiyuan/anaconda3/envs/torch19/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xuzhiyuan/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/distributed/run.py", line 637, in <module>
    main()
  File "/home/xuzhiyuan/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/distributed/run.py", line 629, in main
    run(args)
  File "/home/xuzhiyuan/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/distributed/run.py", line 621, in run
    elastic_launch(
  File "/home/xuzhiyuan/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/xuzhiyuan/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/home/xuzhiyuan/anaconda3/envs/torch19/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
***************************************
       train_retrieval.py FAILED
=======================================
Root Cause:
[0]:
  time: 2022-08-21_21:41:48
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 16500)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
[1]:
  time: 2022-08-21_21:41:48
  rank: 1 (local_rank: 1)
  exitcode: 1 (pid: 16501)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
[2]:
  time: 2022-08-21_21:41:48
  rank: 2 (local_rank: 2)
  exitcode: 1 (pid: 16502)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
[3]:
  time: 2022-08-21_21:41:48
  rank: 3 (local_rank: 3)
  exitcode: 1 (pid: 16503)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
***************************************

*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
'''

**Comment by SKBL5694** [comment]
I found that the problem was caused by insufficient video memory, but the related error was not thrown

**Comment by shivangibithel** [comment]
Hi @SKBL5694 

I am getting the same error while evaluating and train on my own dataset that tensors are not on same device 3 times before the process raising another exception and stopped.

How did you solve this issue?
